name: Continuous Deployment VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: SSH into the VM and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWD }}
        script: |
          # Remove previous code and Dockerfile
          rm -rf code

          # Copy code and Dockerfile to the VM
          mkdir code
          cp -r ./* code/

          # Build and run the Docker image on the VM
          cd code
          docker build -t takeiteasy-backend .
          docker stop tie-backend || true
          docker rm tie-backend || true
          docker run -d --name tie-backend -p 8080:8080 takeiteasy-backend:latest
