name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build with Maven
        working-directory: backend
        run: mvn clean package  

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: take-it-easy-388521
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: gcr.io/take-it-easy-388521/takeiteasy_backend_spring_tie:latest
          build-args: |
            HTTP_PORT=8080

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/take-it-easy-388521/takeiteasy_backend_spring_tie:latest
          service: takeiteasy-backend
          region: europe-southwest1
          # platform: managed
          # allow-unauthenticated: true
          env_vars: |
              FOO=bar
              ZIP=zap
