# This is a basic workflow to help you get started with Actions

name: Continuous integration - Staging Environment

# Controls when the workflow will run
on:
  push:
    branches: [ main ]  # Rever isto depois
  pull_request:
    branches: [ main ]  # Rever isto depois
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to staging environment
        run: echo Hello, world!
      